[workspace]
resolver = "2"
members = [
    "crates/fwknox-proto",
    "crates/fwknox-config",
    "crates/fwknox-replay",
    "crates/fwknox-firewall",
    "crates/fwknox-capture",
    "crates/fwknox-sandbox",
    "crates/fwknox-privsep",
    "crates/fwknox-client",
    "crates/fwknox-daemon",
    "tests/integration",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
authors = []
repository = "https://github.com/nsprd/fwknox"
homepage = "https://github.com/nsprd/fwknox"
readme = "README.md"

[workspace.dependencies]
ring         = "0.17.14"
rmp-serde    = "1.3.1"
serde        = { version = "1.0.228", features = ["derive"] }
serde_json   = "1.0.149"
thiserror    = "2.0.18"
base64       = "0.22.1"
zeroize      = { version = "1.8.2", features = ["zeroize_derive"] }
toml         = "1.1.2+spec-1.1.0"
ipnet        = { version = "2.12.0", features = ["serde"] }
humantime-serde = "1.1.1"
hex          = "0.4.3"
lru          = "0.16.3"
tempfile     = "3.27.0"
fwknox-proto  = { path = "crates/fwknox-proto" }
fwknox-config = { path = "crates/fwknox-config" }
fwknox-replay   = { path = "crates/fwknox-replay" }
fwknox-firewall = { path = "crates/fwknox-firewall" }
fwknox-capture  = { path = "crates/fwknox-capture" }
tracing         = "0.1.44"
nftables        = "0.6.3"
clap                = { version = "4.6.0", features = ["derive"] }
signal-hook         = "0.4.4"
tracing-subscriber  = { version = "0.3.23", features = ["env-filter"] }
fwknox-client       = { path = "crates/fwknox-client" }
fwknox-daemon       = { path = "crates/fwknox-daemon" }
caps                = "0.5.6"
nix                 = { version = "0.31.2", features = ["user", "fs", "process", "signal", "socket"] }
landlock            = "0.4.4"
sd-notify           = "0.5.0"
fwknox-sandbox      = { path = "crates/fwknox-sandbox" }
seccompiler         = "0.4"
libc                = "0.2"
fwknox-privsep      = { path = "crates/fwknox-privsep" }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
duration_suboptimal_units = "allow"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
