[package]
name = "fwknox-sandbox"
description = "fwknox security hardening: capabilities, privdrop, landlock, sd_notify"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
