[package]
name = "fwknox-daemon"
description = "fwknox daemon library and binary"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
caps.workspace = true
clap.workspace = true
fwknox-capture.workspace = true
fwknox-config.workspace = true
fwknox-firewall.workspace = true
fwknox-proto.workspace = true
fwknox-replay.workspace = true
fwknox-sandbox.workspace = true
signal-hook.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
base64.workspace = true
tempfile.workspace = true

[[bin]]
name = "fwknoxd"
path = "src/bin/fwknoxd.rs"
